/* Datos turísticos de Córdoba, España */

const PLACES = [
  {
    id: "mezquita",
    slug: "mezquita-catedral",
    nombre: "Mezquita-Catedral de Córdoba",
    categoria: "Monumento",
    icono: "landmark",
    lat: 37.8790,
    lng: -4.7794,
    imagen:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Mosque_Cordoba_edited.jpg/500px-Mosque_Cordoba_edited.jpg",
    descripcion:
      "Patrimonio de la Humanidad y símbolo máximo de Córdoba. Antigua mezquita omeya con un impresionante bosque de columnas y arcos bicolores, con una catedral renacentista en su interior.",
    horario: "Lun-Sáb 10:00-19:00, Dom 8:30-11:30 y 15:00-19:00",
    precio: "13€ (visita diurna), gratis 8:30-9:30 (excepto domingos)",
    ticketUrl: "https://tickets.mezquita-catedraldecordoba.es/",
    galeria: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Mosque_Cordoba_edited.jpg/500px-Mosque_Cordoba_edited.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Mezquita-catedral_de_C%C3%B3rdoba_interior_17.jpg/500px-Mezquita-catedral_de_C%C3%B3rdoba_interior_17.jpg",
    ],
    tiempoVisita: "1-1,5 horas",
    comoLlegar: "En pleno centro histórico; 10 min a pie desde la Plaza de las Tendillas",
    porQueVisitar:
      "Es el monumento más importante de Córdoba y una de las mayores joyas del arte islámico en Occidente: un bosque de más de 850 columnas con arcos bicolores que no se parece a nada más en el mundo.",
    historia:
      "Construida a partir del año 785 sobre una antigua basílica visigoda, la mezquita se fue ampliando durante dos siglos hasta convertirse en una de las más grandes del islam. Tras la conquista cristiana de 1236 se consagró como catedral, y en el siglo XVI se insertó en su centro una catedral renacentista, decisión que generó polémica ya en su época. Desde 1984 es Patrimonio de la Humanidad.",
    consejoLocal: [
      "Entra a primera hora de la mañana para verla casi vacía y con buena luz.",
      "El Patio de los Naranjos, gratuito, ya merece una parada aunque no entres al interior.",
      "Combínala con un paseo por la Judería, a solo dos minutos andando.",
    ],
    esGratis: false,
    imprescindible: true,
    accesibilidad: "Accesible en silla de ruedas por la puerta principal; consulta rampas puntuales en la web oficial.",
  },
  {
    id: "alcazar",
    slug: "alcazar-de-los-reyes-cristianos",
    nombre: "Alcázar de los Reyes Cristianos",
    categoria: "Monumento",
    icono: "landmark",
    lat: 37.8752333,
    lng: -4.7830566,
    imagen:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Spain_Cordoba_quality_image.jpg/500px-Spain_Cordoba_quality_image.jpg",
    descripcion:
      "Fortaleza medieval que fue residencia de los Reyes Católicos. Destacan sus jardines andalusíes con estanques, y las murallas con vistas a la ciudad.",
    horario: "Mar-Dom 8:15-20:00 (verano), horarios reducidos en invierno",
    precio: "5€, gratis los martes tarde (según temporada)",
    ticketUrl: "https://alcazardelosreyescristianos.cordoba.es/",
    galeria: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Spain_Cordoba_quality_image.jpg/500px-Spain_Cordoba_quality_image.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Gardens_of_the_Alc%C3%A1zar_de_los_Reyes_Cristianos_-_C%C3%B3rdoba%2C_Spain.jpg/500px-Gardens_of_the_Alc%C3%A1zar_de_los_Reyes_Cristianos_-_C%C3%B3rdoba%2C_Spain.jpg",
    ],
    tiempoVisita: "1-1,5 horas",
    comoLlegar: "A 5 min a pie de la Mezquita, junto al río",
    porQueVisitar:
      "Sus jardines andalusíes escalonados con estanques y surtidores son de los más bonitos de España, y las murallas ofrecen algunas de las mejores vistas de la ciudad.",
    historia:
      "Construido en el siglo XIV sobre restos de una fortaleza almohade anterior, fue residencia de los Reyes Católicos, desde donde planificaron la conquista de Granada y recibieron a Cristóbal Colón antes de su viaje a América. Posteriormente fue sede del Tribunal de la Inquisición durante más de tres siglos, y a comienzos del siglo XX funcionó incluso como prisión.",
    consejoLocal: [
      "Sube a la Torre del Homenaje para las mejores vistas del conjunto de jardines.",
      "Confirma en la web oficial si hay descuento o entrada gratuita los martes tarde según la temporada.",
      "Al atardecer, la luz sobre los estanques es especialmente bonita.",
    ],
    esGratis: false,
    imprescindible: true,
    accesibilidad: "El palacio y buena parte de los jardines son accesibles; algunas zonas de las murallas tienen escalones estrechos.",
  },
  {
    id: "puente-romano",
    slug: "puente-romano",
    nombre: "Puente Romano",
    categoria: "Monumento",
    icono: "landmark",
    lat: 37.8766472,
    lng: -4.7779624,
    imagen:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Puente_Romano_Cordoba.jpg/500px-Puente_Romano_Cordoba.jpg",
    descripcion:
      "Puente de origen romano (siglo I a.C.) sobre el río Guadalquivir, con vistas privilegiadas de la Mezquita y la Torre de la Calahorra. Uno de los rincones más fotografiados de la ciudad.",
    horario: "Abierto 24h (peatonal)",
    precio: "Gratis",
    galeria: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Puente_Romano_Cordoba.jpg/500px-Puente_Romano_Cordoba.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Puente_sobre_el_Guadalquivir_de_noche_con_la_Mezquita_de_C%C3%B3rdoba_iluminada_al_fondo.jpg/500px-Puente_sobre_el_Guadalquivir_de_noche_con_la_Mezquita_de_C%C3%B3rdoba_iluminada_al_fondo.jpg",
    ],
    tiempoVisita: "20-30 min",
    comoLlegar: "Justo a los pies de la Mezquita, cruzando la Puerta del Puente",
    porQueVisitar:
      "Es la imagen más fotografiada de Córdoba: un puente de origen romano con vistas directas a la Mezquita y la Torre de la Calahorra a ambos lados del Guadalquivir.",
    historia:
      "Construido en el siglo I a.C. como parte de la Vía Augusta, fue durante casi dos mil años el único puente de la ciudad sobre el Guadalquivir. Ha sido reconstruido varias veces a lo largo de la historia, conservando su trazado y 16 arcos originales. En su extremo sur se alza la estatua de San Rafael, patrón de la ciudad.",
    consejoLocal: [
      "El atardecer, con la Mezquita iluminada de fondo, es el mejor momento para fotografiarlo.",
      "Camina hasta el centro exacto del puente para el encuadre clásico.",
      "Desde la Torre de la Calahorra, en la otra orilla, la perspectiva conjunta es aún mejor.",
    ],
    esGratis: true,
    imprescindible: true,
    accesibilidad: "Totalmente accesible, superficie plana y peatonal.",
  },
  {
    id: "juderia",
    slug: "juderia-de-cordoba",
    nombre: "Judería de Córdoba",
    categoria: "Barrio histórico",
    icono: "map-pin",
    lat: 37.8798,
    lng: -4.7814,
    imagen:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Cordoba%2C_Spain_%2811174916253%29.jpg/500px-Cordoba%2C_Spain_%2811174916253%29.jpg",
    descripcion:
      "Barrio medieval de calles estrechas y encaladas, patios floridos y plazoletas con encanto. Fue el antiguo barrio judío y hoy es Patrimonio de la Humanidad.",
    horario: "Abierto 24h",
    precio: "Gratis",
    galeria: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Cordoba%2C_Spain_%2811174916253%29.jpg/500px-Cordoba%2C_Spain_%2811174916253%29.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Calleja_de_las_Flores_%28C%C3%B3rdoba%29.jpg/500px-Calleja_de_las_Flores_%28C%C3%B3rdoba%29.jpg",
    ],
    tiempoVisita: "1-2 horas paseando",
    comoLlegar: "Rodea la Mezquita por el norte y el oeste",
    porQueVisitar:
      "Perderse por sus callejones blancos, patios floridos y plazoletas es de las experiencias más entrañables de Córdoba, sobre todo si viajas en primavera.",
    historia:
      "Fue el barrio judío de la ciudad desde la Edad Media hasta la expulsión de 1492, y conserva su trazado original de calles estrechas e irregulares pensado para dar sombra. Hoy conviven en él la Sinagoga, la Casa de Sefarad, tiendas de artesanía y algunas de las tabernas más antiguas de la ciudad.",
    consejoLocal: [
      "La Calleja de las Flores, con la torre de la Mezquita enmarcada al fondo, es la foto más icónica del barrio.",
      "Ve temprano o al final de la tarde para evitar la multitud de grupos guiados.",
      "En mayo, durante el Festival de los Patios, muchas casas particulares abren sus patios floridos.",
    ],
    esGratis: true,
    imprescindible: true,
    accesibilidad: "Calles empedradas y estrechas; puede resultar incómodo para sillas de ruedas o carritos en algunos tramos.",
  },
  {
    id: "sinagoga",
    slug: "sinagoga-de-cordoba",
    nombre: "Sinagoga de Córdoba",
    categoria: "Monumento",
    icono: "landmark",
    lat: 37.8798101,
    lng: -4.7833842,
    imagen:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Sinagoga_de_C%C3%B3rdoba_%28Espa%C3%B1a%29.jpg/500px-Sinagoga_de_C%C3%B3rdoba_%28Espa%C3%B1a%29.jpg",
    descripcion:
      "Una de las tres sinagogas medievales mejor conservadas de España, con decoración mudéjar de yeserías. Pequeña joya escondida en la Judería.",
    horario: "Mar-Dom 9:00-21:00",
    precio: "Gratis (ciudadanos UE), 0,30€ resto",
    tiempoVisita: "15-20 min",
    comoLlegar: "En el corazón de la Judería, a 3 min de la Mezquita",
    porQueVisitar:
      "Es una de las tres únicas sinagogas medievales que quedan en pie en toda España, con una decoración de yeserías mudéjares excepcional para su reducido tamaño.",
    historia:
      "Construida en 1315, es un raro ejemplo de arquitectura mudéjar aplicada a un edificio religioso judío. Tras la expulsión de los judíos en 1492 fue reutilizada como hospital, ermita y hasta escuela, lo que probablemente ayudó a conservarla. Fue declarada Monumento Nacional en 1885.",
    consejoLocal: [
      "Al ser tan pequeña, se visita rápido: combínala con la Casa de Sefarad, a un minuto andando.",
      "Fíjate en las inscripciones en hebreo de los muros, entre las pocas que se conservan de su época.",
    ],
    esGratis: true,
    imprescindible: false,
    accesibilidad: "Acceso con un escalón en la entrada; interior de un único ambiente sin desniveles.",
  },
  {
    id: "palacio-viana",
    slug: "palacio-de-viana",
    nombre: "Palacio de Viana",
    categoria: "Museo",
    icono: "building",
    lat: 37.8887,
    lng: -4.7743,
    imagen:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Portada_del_Palacio_de_Viana%2C_C%C3%B3rdoba.jpg/500px-Portada_del_Palacio_de_Viana%2C_C%C3%B3rdoba.jpg",
    descripcion:
      "Palacio-museo con doce patios distintos, cada uno con su propio estilo y jardín. Uno de los mejores lugares para entender la tradición de los patios cordobeses.",
    horario: "Lun-Sáb 10:00-19:00, Dom 10:00-15:00",
    precio: "8€ (patios), 10€ (patios + casa)",
    ticketUrl: "https://entradas.palaciodeviana.com/",
    galeria: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Portada_del_Palacio_de_Viana%2C_C%C3%B3rdoba.jpg/500px-Portada_del_Palacio_de_Viana%2C_C%C3%B3rdoba.jpg",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Palacio_de_Viana_%28C%C3%B3rdoba%29._Patio_de_Recibo.jpg/500px-Palacio_de_Viana_%28C%C3%B3rdoba%29._Patio_de_Recibo.jpg",
    ],
    tiempoVisita: "1-1,5 horas",
    comoLlegar: "En el barrio de Santa Marina, a 10-15 min a pie del centro",
    porQueVisitar:
      "Ningún otro lugar de Córdoba reúne tantos patios distintos bajo un mismo techo: doce, cada uno con su propio carácter, y una de las mejores formas de entender la tradición floral cordobesa sin coincidir con las aglomeraciones del Festival de los Patios.",
    historia:
      "Palacio señorial construido a partir del siglo XIV y ampliado por sucesivas generaciones familiares hasta el siglo XVIII, cuando pasó a manos de los marqueses de Viana. Fue donado a una entidad bancaria en 1980 y convertido en museo, conservando mobiliario, tapices y una importante colección de armas y porcelanas.",
    consejoLocal: [
      "Si tienes poco tiempo, elige la visita de 'solo patios', más económica y suficiente para disfrutar lo esencial.",
      "La glicina en flor (abril-mayo) en el Patio de la Alberca es uno de los rincones más fotografiados.",
      "Combina la visita con un paseo por la cercana Plaza de Capuchinos y el Cristo de los Faroles.",
    ],
    esGratis: false,
    imprescindible: true,
    accesibilidad: "Los patios en planta baja son accesibles; el interior de la casa tiene escaleras sin ascensor.",
  },
  {
    id: "templo-romano",
    slug: "templo-romano",
    nombre: "Templo Romano",
    categoria: "Monumento",
    icono: "landmark",
    lat: 37.8847854,
    lng: -4.7763889,
    imagen:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Templo_romano_C%C3%B3rdoba_2025.jpg/500px-Templo_romano_C%C3%B3rdoba_2025.jpg",
    descripcion:
      "Restos monumentales de un templo romano del siglo I, con columnas corintias reconstruidas, ubicado junto al Ayuntamiento.",
    horario: "Exterior visible 24h",
    precio: "Gratis",
    tiempoVisita: "10 min",
    comoLlegar: "Junto al Ayuntamiento, a 5 min de la Plaza de las Tendillas",
    porQueVisitar:
      "Sus columnas corintias reconstruidas, iluminadas de noche, son un recordatorio inesperado de que Córdoba (Corduba) fue capital de la Bética romana.",
    historia:
      "Data del siglo I d.C. y estuvo dedicado al culto imperial. Permaneció oculto bajo edificios posteriores hasta que fue descubierto en 1950 durante unas obras de ampliación del Ayuntamiento, y sus columnas se reconstruyeron parcialmente para dar idea de su volumen original.",
    consejoLocal: [
      "De noche, iluminado, es uno de los rincones con más encanto del centro y casi siempre está vacío.",
      "Se ve perfectamente desde la calle, sin necesidad de entrada ni horario.",
    ],
    esGratis: true,
    imprescindible: false,
    accesibilidad: "Se observa desde la acera; totalmente accesible al ser un exterior a pie de calle.",
  },
  {
    id: "calahorra",
    slug: "torre-de-la-calahorra",
    nombre: "Torre de la Calahorra",
    categoria: "Museo",
    icono: "building",
    lat: 37.8756267,
    lng: -4.7765897,
    imagen:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/Torre_de_la_Calahorra_%28C%C3%B3rdoba%2C_Espa%C3%B1a%29.jpg/500px-Torre_de_la_Calahorra_%28C%C3%B3rdoba%2C_Espa%C3%B1a%29.jpg",
    descripcion:
      "Fortaleza árabe al otro lado del Puente Romano que alberga un museo sobre la convivencia de las tres culturas (musulmana, judía y cristiana) en la Córdoba medieval.",
    horario: "Todos los días 10:00-18:00 (varía según temporada)",
    precio: "4,50€",
    ticketUrl: "https://www.torrecalahorra.es/horario-tarifas/",
    tiempoVisita: "45 min - 1 hora",
    comoLlegar: "Al otro lado del Puente Romano, orilla sur del río",
    porQueVisitar:
      "Además del museo sobre la convivencia de culturas, subir a su torre ofrece una de las postales más bonitas de Córdoba: el Puente Romano y la Mezquita desde el otro lado del río.",
    historia:
      "Fortificación de origen almohade (siglo XII) que defendía el acceso sur al puente romano. Fue reconstruida por orden de Enrique II de Castilla en el siglo XIV para controlar la entrada a la ciudad. Desde 1936 alberga un museo dedicado a la convivencia de musulmanes, judíos y cristianos en la Córdoba medieval.",
    consejoLocal: [
      "Sube a la terraza superior para la mejor vista del puente y la Mezquita juntos.",
      "Es una buena opción para el mediodía, cuando el sol de frente dificulta las fotos desde el puente.",
    ],
    esGratis: false,
    imprescindible: false,
    accesibilidad: "El interior tiene escaleras estrechas de caracol en varios tramos; no accesible en silla de ruedas.",
  },
  {
    id: "corredera",
    slug: "plaza-de-la-corredera",
    nombre: "Plaza de la Corredera",
    categoria: "Plaza",
    icono: "map-pin",
    lat: 37.8835670,
    lng: -4.7744879,
    imagen:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Plaza_de_la_Corredera_desde_el_aire_%28C%C3%B3rdoba%2C_Espa%C3%B1a%29_%28cropped%29.jpg/500px-Plaza_de_la_Corredera_desde_el_aire_%28C%C3%B3rdoba%2C_Espa%C3%B1a%29_%28cropped%29.jpg",
    descripcion:
      "Gran plaza porticada de estilo castellano, poco habitual en Andalucía. Antiguo escenario de corridas de toros y hoy llena de bares y un mercado de abastos.",
    horario: "Abierto 24h",
    precio: "Gratis",
    tiempoVisita: "20-30 min",
    comoLlegar: "A 8 min a pie de la Mezquita, en el barrio de la Axerquía",
    porQueVisitar:
      "Es la única plaza mayor porticada de estilo castellano en toda Andalucía, con un ambiente de tapeo muy auténtico, lejos del circuito turístico más denso.",
    historia:
      "Construida en el siglo XVII sobre el antiguo Corral de Comedias y una plaza de mercado, fue durante siglos escenario de corridas de toros, ejecuciones públicas y fiestas reales. Hoy conserva su mercado de abastos cubierto en uno de sus laterales.",
    consejoLocal: [
      "Por las mañanas hay mercado de abastos; por las tardes-noches se llena de terrazas.",
      "Es un buen lugar para tapear alejado de los precios turísticos de la zona de la Mezquita.",
    ],
    esGratis: true,
    imprescindible: false,
    accesibilidad: "Plaza completamente llana y accesible, con soportales.",
  },
  {
    id: "medina-azahara",
    slug: "medina-azahara",
    nombre: "Medina Azahara",
    categoria: "Yacimiento arqueológico",
    icono: "compass",
    lat: 37.8859775,
    lng: -4.8669949,
    imagen:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Puerta_del_primer_ministro.JPG/500px-Puerta_del_primer_ministro.JPG",
    descripcion:
      "Ciudad palatina califal del siglo X, a unos 8 km del centro. Patrimonio de la Humanidad. Sus ruinas monumentales muestran el esplendor del Califato de Córdoba.",
    horario: "Mar-Sáb 9:00-18:30, Dom 9:00-15:30 (varía según temporada)",
    precio: "Gratis (entrada con reserva previa), autobús turístico opcional",
    ticketUrl: "https://www.museosdeandalucia.es/web/conjuntoarqueologicomadinatalzahra/",
    galeria: [
      "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Puerta_del_primer_ministro.JPG/500px-Puerta_del_primer_ministro.JPG",
      "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Sal%C3%B3n_Rico_-_Medina_Azahara%2C_C%C3%B3rdoba.jpg/500px-Sal%C3%B3n_Rico_-_Medina_Azahara%2C_C%C3%B3rdoba.jpg",
    ],
    tiempoVisita: "2-3 horas (incluye traslado)",
    comoLlegar: "A 8 km del centro; autobús turístico desde el Centro de Interpretación (Paseo de la Victoria) o coche propio",
    porQueVisitar:
      "Es el yacimiento arqueológico más importante de la España musulmana: una ciudad palatina entera construida para deslumbrar, que muestra la escala real del poder del Califato de Córdoba en su momento de máximo esplendor.",
    historia:
      "Mandada construir en el año 936 por Abderramán III para trasladar la capital del califato fuera de Córdoba, llegó a albergar administración, ejército y una lujosa corte con miles de habitantes. Fue destruida y saqueada en las guerras civiles de comienzos del siglo XI, apenas 70 años después de su fundación, y quedó sepultada y olvidada durante siglos hasta que las excavaciones sistemáticas comenzaron en 1911. Se calcula que solo se ha excavado una décima parte del yacimiento total.",
    consejoLocal: [
      "Reserva la entrada gratuita con antelación en la web oficial; las plazas se agotan en temporada alta.",
      "Empieza siempre por el museo del centro de interpretación: ayuda mucho a entender las ruinas.",
      "Ve a primera hora en verano: apenas hay sombra en el yacimiento.",
    ],
    esGratis: true,
    imprescindible: true,
    accesibilidad: "El centro de interpretación es accesible; el yacimiento tiene tramos de terreno irregular.",
  },
  {
    id: "molino-albolafia",
    slug: "molino-de-la-albolafia",
    nombre: "Molino de la Albolafia",
    categoria: "Monumento",
    icono: "landmark",
    lat: 37.8767787,
    lng: -4.7799884,
    imagen:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Molino_de_la_Albolafia_%28C%C3%B3rdoba%2C_Espa%C3%B1a%29.jpg/500px-Molino_de_la_Albolafia_%28C%C3%B3rdoba%2C_Espa%C3%B1a%29.jpg",
    descripcion:
      "Antigua noria islámica de origen almohade sobre el Guadalquivir, junto al Puente Romano. Su rueda figura en el escudo de la ciudad desde el siglo XIV.",
    horario: "Se contempla desde el exterior las 24h",
    precio: "Gratis",
    tiempoVisita: "10 min",
    comoLlegar: "Junto al Puente Romano, orilla norte",
    porQueVisitar:
      "Es uno de los símbolos históricos de la ciudad (aparece en su escudo) y un buen recordatorio de la ingeniería hidráulica andalusí.",
    historia:
      "De origen almohade (siglos XII-XIII), se utilizó para elevar agua del Guadalquivir hasta los jardines del Alcázar. Cuenta la leyenda que la reina Isabel la Católica ordenó desmontar parte del mecanismo porque el ruido de la rueda no la dejaba dormir.",
    consejoLocal: [
      "Se ve muy bien desde el propio Puente Romano; no hace falta acercarse más.",
      "Combínalo con la Puerta del Puente, a menos de un minuto caminando.",
    ],
    esGratis: true,
    imprescindible: false,
    accesibilidad: "Se observa desde el puente o la orilla; exterior accesible.",
  },
  {
    id: "puerta-puente",
    slug: "puerta-del-puente",
    nombre: "Puerta del Puente",
    categoria: "Monumento",
    icono: "landmark",
    lat: 37.8777530,
    lng: -4.7791345,
    imagen:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Puerta_del_Puente%2C_C%C3%B3rdoba%2C_Espa%C3%B1a.jpg/500px-Puerta_del_Puente%2C_C%C3%B3rdoba%2C_Espa%C3%B1a.jpg",
    descripcion:
      "Antigua puerta de la muralla romana, remodelada en el siglo XVI a modo de arco triunfal para la visita de Felipe II. Incluye un mirador con vistas al conjunto monumental.",
    horario: "Lun-Dom 10:00-14:00 (mirador y sala de exposiciones)",
    precio: "1€ (gratis menores de 4 años)",
    tiempoVisita: "15-20 min",
    comoLlegar: "En el extremo norte del Puente Romano",
    porQueVisitar:
      "Su mirador interior ofrece una perspectiva elevada poco habitual del Puente Romano y la Mezquita, por un precio simbólico.",
    historia:
      "Construida en el siglo XVI por Hernán Ruiz III como arco triunfal para la visita de Felipe II, sustituyó a una puerta medieval anterior de la muralla romana. Formaba parte del recinto amurallado que protegía el acceso al puente.",
    consejoLocal: [
      "Subir al mirador interior es rápido y barato, y regala una vista distinta a la del propio puente.",
      "Buena parada de 10 minutos si vienes o vas hacia la Torre de la Calahorra.",
    ],
    esGratis: false,
    imprescindible: false,
    accesibilidad: "El mirador se accede por escaleras; no apto para sillas de ruedas.",
  },
  {
    id: "banos-califales",
    slug: "banos-del-alcazar-califal",
    nombre: "Baños del Alcázar Califal",
    categoria: "Museo",
    icono: "building",
    lat: 37.8779,
    lng: -4.7823,
    imagen:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Ba%C3%B1os_califales_de_C%C3%B3rdoba_03.jpg/500px-Ba%C3%B1os_califales_de_C%C3%B3rdoba_03.jpg",
    descripcion:
      "Baños árabes del siglo X mandados construir por Al-Hakam II junto al antiguo Alcázar andalusí, con sus salas fría, templada y caliente bien conservadas.",
    horario: "Mar-Vie 8:15-20:15, Sáb 9:30-17:30, Dom y festivos 8:15-14:15 (invierno; varía en verano)",
    precio: "3€ (estudiantes 1,50€, menores de 13 gratis)",
    tiempoVisita: "30-45 min",
    comoLlegar: "Junto al Alcázar, en el Campo Santo de los Mártires",
    porQueVisitar:
      "Es uno de los conjuntos termales islámicos mejor conservados de España, y ayuda a imaginar la vida cotidiana de la corte califal más allá de los grandes monumentos.",
    historia:
      "Construidos en el siglo X por orden de Al-Hakam II junto al Alcázar andalusí, seguían el modelo de las termas romanas con salas fría, templada y caliente. Permanecieron ocultos hasta que unas obras de jardinería los sacaron a la luz en 1903; se excavaron en profundidad entre 1961 y 1964.",
    consejoLocal: [
      "Se visita en poco tiempo: combínalo con el Alcázar, justo al lado.",
      "Fíjate en las estrellas caladas de las bóvedas, que dejaban pasar la luz para marcar las horas.",
    ],
    esGratis: false,
    imprescindible: false,
    accesibilidad: "Espacio en un único nivel, aunque con algunos escalones puntuales entre salas.",
  },
  {
    id: "tendillas",
    slug: "plaza-de-las-tendillas",
    nombre: "Plaza de las Tendillas",
    categoria: "Plaza",
    icono: "map-pin",
    lat: 37.884491,
    lng: -4.779565,
    imagen:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Plaza_de_las_Tendillas._Panoramica.jpg/500px-Plaza_de_las_Tendillas._Panoramica.jpg",
    descripcion:
      "El corazón comercial y social de la Córdoba moderna, con la estatua ecuestre del Gran Capitán y un curioso reloj que suena por soleares en vez de campanadas.",
    horario: "Abierto 24h",
    precio: "Gratis",
    tiempoVisita: "15-20 min",
    comoLlegar: "En el centro comercial de la ciudad, a 10 min a pie de la Mezquita",
    porQueVisitar:
      "Es el punto de encuentro de los cordobeses de toda la vida, con un reloj tan peculiar que merece la pena esperar a que suene en punto.",
    historia:
      "Su nombre viene de las pequeñas tiendas ('tendillas') que tuvo la Orden de Calatrava desde el siglo XIV. Adoptó su forma actual en los años 20 del siglo XX, tras derribar el antiguo Hotel Suizo, y desde 1961 su reloj toca las horas con una guitarra flamenca en vez de campanadas.",
    consejoLocal: [
      "Si estás cerca en una hora en punto, párate un momento a escuchar el reloj por soleares.",
      "Es un buen punto de referencia para orientarse: de aquí salen las principales calles comerciales.",
    ],
    esGratis: true,
    imprescindible: false,
    accesibilidad: "Plaza totalmente llana y accesible.",
  },
  {
    id: "casa-sefarad",
    slug: "casa-de-sefarad",
    nombre: "Casa de Sefarad",
    categoria: "Museo",
    icono: "building",
    lat: 37.87986,
    lng: -4.78331,
    imagen:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Casa_de_Sefarad_%28C%C3%B3rdoba%2C_Spain%29.jpg/500px-Casa_de_Sefarad_%28C%C3%B3rdoba%2C_Spain%29.jpg",
    descripcion:
      "Centro cultural en plena Judería dedicado a recuperar la memoria sefardí, con salas sobre la sinagoga, Maimónides, la música y la vida cotidiana judeoespañola.",
    horario: "Mar-Sáb 11:00-18:00",
    precio: "4,50€ (estudiantes 3,50€)",
    tiempoVisita: "45 min - 1 hora",
    comoLlegar: "En plena Judería, a 2 min de la Sinagoga",
    porQueVisitar:
      "Complementa perfectamente la visita a la Sinagoga, con salas temáticas sobre la vida y la cultura judeoespañola que ayudan a entender el barrio en el que estás caminando.",
    historia:
      "Abrió en 2006 en un conjunto de casas del siglo XIV rehabilitadas, muy cerca de la Sinagoga. Su colección reúne objetos rituales, documentos y música tradicional sefardí, además de una sala dedicada al filósofo cordobés Maimónides, una de las figuras judías más importantes de la Edad Media.",
    consejoLocal: [
      "Visítala justo después de la Sinagoga para tener el contexto histórico fresco.",
      "Algunos días organizan pequeños conciertos de música sefardí: consulta la agenda en su web.",
    ],
    esGratis: false,
    imprescindible: false,
    accesibilidad: "Casa histórica con varios desniveles y escalones entre salas.",
  },
  {
    id: "museo-arqueologico",
    slug: "museo-arqueologico-y-etnologico",
    nombre: "Museo Arqueológico y Etnológico",
    categoria: "Museo",
    icono: "building",
    lat: 37.881966,
    lng: -4.777881,
    imagen:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Portada_del_Museo_Arqueol%C3%B3gico_y_Etnol%C3%B3gico_de_C%C3%B3rdoba.jpg/500px-Portada_del_Museo_Arqueol%C3%B3gico_y_Etnol%C3%B3gico_de_C%C3%B3rdoba.jpg",
    descripcion:
      "Colección arqueológica y etnológica alojada en el renacentista Palacio de los Páez de Castillejo, con importantes piezas de época romana e islámica.",
    horario: "Mar-Sáb 9:00-20:00, Dom y festivos 9:00-15:00 (horario reducido en verano)",
    precio: "Gratis (ciudadanos UE), 1,50€ resto",
    tiempoVisita: "1-1,5 horas",
    comoLlegar: "A 5 min a pie de la Plaza de las Tendillas",
    porQueVisitar:
      "Reúne algunas de las piezas romanas e islámicas más importantes encontradas en la ciudad, en un edificio renacentista que es una obra de arte en sí mismo.",
    historia:
      "Instalado desde 1868 en el Palacio de los Páez de Castillejo, un palacio renacentista del siglo XVI diseñado por Hernán Ruiz II. Sus fondos abarcan desde la prehistoria hasta la época islámica, con una notable colección de mosaicos, esculturas romanas y cerámica califal.",
    consejoLocal: [
      "La entrada es gratuita para ciudadanos de la UE: lleva el DNI o pasaporte.",
      "No te pierdas el patio interior del propio palacio, con sus arcos mudéjares.",
    ],
    esGratis: true,
    imprescindible: false,
    accesibilidad: "Cuenta con ascensor y accesos adaptados en la mayor parte del recorrido.",
  },
  {
    id: "san-lorenzo",
    slug: "iglesia-de-san-lorenzo",
    nombre: "Iglesia de San Lorenzo",
    categoria: "Iglesia",
    icono: "landmark",
    lat: 37.888559,
    lng: -4.768894,
    imagen:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/d/df/Iglesia_de_San_Lorenzo_-_C%C3%B3rdoba_%28Espa%C3%B1a%29.jpg/500px-Iglesia_de_San_Lorenzo_-_C%C3%B3rdoba_%28Espa%C3%B1a%29.jpg",
    descripcion:
      "Una de las iglesias fernandinas del siglo XIII, de estilo gótico-mudéjar, con un notable rosetón y un campanario renacentista obra de Hernán Ruiz II.",
    horario: "Abierta al culto; horario de visita variable",
    precio: "Gratis",
    tiempoVisita: "15-20 min",
    comoLlegar: "A 15 min a pie al noreste del centro, barrio de San Lorenzo",
    porQueVisitar:
      "Es de las mejor conservadas entre las 'iglesias fernandinas' de Córdoba, con un rosetón gótico que pocos turistas llegan a ver por estar fuera del circuito más transitado.",
    historia:
      "Construida en el siglo XIII tras la conquista cristiana de la ciudad, sobre una antigua mezquita de barrio, como parte del programa de doce iglesias que Fernando III mandó levantar. Su campanario renacentista, añadido en el siglo XVI, es obra de Hernán Ruiz II, el mismo arquitecto de la torre de la Mezquita-Catedral.",
    consejoLocal: [
      "Se sale un poco del centro turístico, así que suele estar tranquila.",
      "Combínala con un paseo por el barrio de San Lorenzo, de los más auténticos y menos masificados.",
    ],
    esGratis: true,
    imprescindible: false,
    accesibilidad: "Acceso con escalón en la puerta principal; interior de nave única sin grandes desniveles.",
  },
  {
    id: "torre-malmuerta",
    slug: "torre-de-la-malmuerta",
    nombre: "Torre de la Malmuerta",
    categoria: "Monumento",
    icono: "landmark",
    lat: 37.891731,
    lng: -4.777658,
    imagen:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Torre_de_la_Malmuerta_%28C%C3%B3rdoba%2C_Espa%C3%B1a%29.jpg/500px-Torre_de_la_Malmuerta_%28C%C3%B3rdoba%2C_Espa%C3%B1a%29.jpg",
    descripcion:
      "Torre albarrana del siglo XV construida para defender la muralla de la Axerquía, envuelta en una célebre leyenda trágica cordobesa.",
    horario: "Se contempla desde el exterior las 24h",
    precio: "Gratis",
    tiempoVisita: "10 min",
    comoLlegar: "A 15 min a pie al norte del centro, junto a la Ronda de los Tejares",
    porQueVisitar:
      "Es una de las torres defensivas mejor conservadas de la antigua muralla, con una leyenda trágica que los cordobeses todavía cuentan.",
    historia:
      "Construida entre 1406 y 1408 por orden de Enrique III de Castilla para reforzar la muralla de la Axerquía, formaba parte del sistema defensivo que rodeaba la ciudad medieval. Su nombre proviene de una leyenda del siglo XIX sobre un noble que, tras matar por error a su esposa creyéndola infiel, quedó atormentado y encerrado en la torre.",
    consejoLocal: [
      "Se ve bien desde la calle sin necesidad de entrar (normalmente no tiene visitas al interior).",
      "Es un buen punto de paso si caminas desde el centro hacia la estación de tren.",
    ],
    esGratis: true,
    imprescindible: false,
    accesibilidad: "Se observa desde el exterior; entorno urbano accesible.",
  },
  {
    id: "caballerizas-reales",
    slug: "caballerizas-reales",
    nombre: "Caballerizas Reales",
    categoria: "Monumento",
    icono: "landmark",
    lat: 37.8765382,
    lng: -4.7832021,
    imagen:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Caballerizas_Reales_de_C%C3%B3rdoba.jpg/500px-Caballerizas_Reales_de_C%C3%B3rdoba.jpg",
    descripcion:
      "Cuadras reales del siglo XVI donde nació la raza de caballo español (Pura Raza Española), junto al Alcázar. Hoy ofrecen espectáculos ecuestres y visitas guiadas.",
    horario: "Mar 10:00-13:30 y 16:30-19:30, Mié-Sáb 10:00-13:30 y 17:30-20:30",
    precio: "16,50€ adultos, 11,50€ niños 3-12 años, gratis menores de 3",
    ticketUrl: "https://caballerizasreales.com/",
    tiempoVisita: "45 min - 1 hora (más si hay espectáculo)",
    comoLlegar: "Junto al Alcázar, a 5 min a pie de la Mezquita",
    porQueVisitar:
      "Es el lugar de nacimiento del caballo andaluz (Pura Raza Español), con una nave que García Lorca comparó con 'una catedral para caballos'.",
    historia:
      "Fundadas en 1572 por Felipe II para criar caballos para la Casa Real, dieron origen al Pura Raza Español cruzando ejemplares locales con caballos árabes y berberiscos. Un incendio a mediados del siglo XVIII obligó a reconstruirlas casi por completo. Fueron declaradas Monumento Histórico Nacional en 1929.",
    consejoLocal: [
      "Si te gustan los caballos, reserva con antelación alguno de los espectáculos ecuestres.",
      "La nave principal, con sus tres naves de bóveda de arista, merece la visita aunque no haya espectáculo.",
    ],
    esGratis: false,
    imprescindible: false,
    accesibilidad: "Nave principal accesible en superficie llana.",
  },
];

const EVENTS = [
  {
    id: "patios-fest",
    nombre: "Festival de los Patios de Córdoba",
    icono: "calendar",
    fecha: "Primeras dos semanas de mayo",
    lugar: "Barrios de San Basilio, Alcázar Viejo y otros",
    descripcion:
      "Los cordobeses abren las puertas de sus patios engalanados con flores en macetas. Patrimonio Inmaterial de la Humanidad por la UNESCO.",
  },
  {
    id: "cruces-mayo",
    nombre: "Festival de las Cruces de Mayo",
    icono: "calendar",
    fecha: "Primeros días de mayo",
    lugar: "Plazas de toda la ciudad",
    descripcion:
      "Cruces engalanadas con flores compiten en distintos barrios, acompañadas de casetas con música y gastronomía típica.",
  },
  {
    id: "feria-salud",
    nombre: "Feria de Nuestra Señora de la Salud",
    icono: "calendar",
    fecha: "Finales de mayo",
    lugar: "Recinto ferial El Arenal",
    descripcion:
      "La gran feria anual de Córdoba, con casetas, atracciones, flamenco y la tradicional feria de día en el Paseo de la Victoria.",
  },
  {
    id: "noche-flamenco",
    nombre: "Noche Blanca del Flamenco",
    icono: "calendar",
    fecha: "Mediados de junio",
    lugar: "Plazas y escenarios de todo el centro histórico",
    descripcion:
      "Una noche entera dedicada al flamenco en directo y gratuito, con decenas de actuaciones repartidas por la ciudad.",
  },
  {
    id: "semana-santa",
    nombre: "Semana Santa de Córdoba",
    icono: "calendar",
    fecha: "Marzo o abril (variable)",
    lugar: "Casco histórico",
    descripcion:
      "Declarada de Interés Turístico Nacional, con procesiones de hermandades centenarias recorriendo las calles del centro.",
  },
  {
    id: "concurso-flamenco",
    nombre: "Concurso Nacional de Arte Flamenco",
    icono: "calendar",
    fecha: "Cada 3 años (próxima edición a confirmar)",
    lugar: "Gran Teatro de Córdoba",
    descripcion:
      "Uno de los certámenes de flamenco más prestigiosos del mundo, celebrado en Córdoba desde 1956.",
  },
];

const FOOD = [
  {
    id: "salmorejo",
    nombre: "Salmorejo cordobés",
    icono: "utensils",
    tipo: "Plato típico",
    imagen: "https://upload.wikimedia.org/wikipedia/commons/e/eb/Salmorejo_cordobes.jpg",
    descripcion:
      "Crema fría de tomate, pan, ajo y aceite de oliva virgen extra, servida con huevo duro y jamón picado. El plato más emblemático de Córdoba.",
    dondeProbar: [
      { collection: "tapas", id: "bodegas-mezquita-cespedes" },
      { collection: "tapas", id: "sociedad-plateros" },
      { collection: "restaurants", id: "casa-pepe-juderia" },
    ],
  },
  {
    id: "flamenquin",
    nombre: "Flamenquín",
    icono: "utensils",
    tipo: "Plato típico",
    imagen:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Flamenqu%C3%ADn%2C_C%C3%B3rdoba%2C_2016.jpg/500px-Flamenqu%C3%ADn%2C_C%C3%B3rdoba%2C_2016.jpg",
    descripcion:
      "Rollo de lomo de cerdo envuelto en jamón serrano, empanado y frito. Se sirve normalmente con patatas fritas y alioli.",
    dondeProbar: [
      { collection: "restaurants", id: "taberna-salinas" },
      { collection: "restaurants", id: "casa-pepe-juderia" },
    ],
  },
  {
    id: "rabo-toro",
    nombre: "Rabo de toro",
    icono: "utensils",
    tipo: "Plato típico",
    imagen:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Rabo_de_toro-Estofado_%2801%29.JPG/500px-Rabo_de_toro-Estofado_%2801%29.JPG",
    descripcion:
      "Guiso tradicional de rabo de toro estofado a fuego lento con vino, verduras y especias, hasta quedar tierno y meloso.",
    dondeProbar: [
      { collection: "restaurants", id: "el-churrasco" },
      { collection: "restaurants", id: "bodegas-campos" },
      { collection: "tapas", id: "casa-rubio" },
    ],
  },
  {
    id: "berenjenas-miel",
    nombre: "Berenjenas con miel de caña",
    icono: "utensils",
    tipo: "Tapa",
    imagen:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Berenjenas_con_miel_de_ca%C3%B1a_La_Gamba_de_ORO.jpg/500px-Berenjenas_con_miel_de_ca%C3%B1a_La_Gamba_de_ORO.jpg",
    descripcion:
      "Berenjenas cortadas en tiras finas, fritas y bañadas en miel de caña. Una tapa dulce-salada muy popular en las tabernas.",
    dondeProbar: [
      { collection: "tapas", id: "casa-rubio" },
      { collection: "restaurants", id: "taberna-salinas" },
      { collection: "restaurants", id: "casa-pepe-juderia" },
    ],
  },
  {
    id: "vino-montilla",
    nombre: "Vino Montilla-Moriles",
    icono: "wine",
    tipo: "Bebida",
    imagen:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Detalle_botellas_Cooperativa_La_Uni%C3%B3n_de_Montilla.jpg/500px-Detalle_botellas_Cooperativa_La_Uni%C3%B3n_de_Montilla.jpg",
    descripcion:
      "Vino con Denominación de Origen propia de la provincia, elaborado con uva Pedro Ximénez. Ideal para acompañar el tapeo.",
    dondeProbar: [
      { collection: "tapas", id: "bodega-guzman" },
      { collection: "tapas", id: "sociedad-plateros" },
    ],
  },
  {
    id: "mazamorra",
    nombre: "Mazamorra cordobesa",
    icono: "utensils",
    tipo: "Plato típico",
    descripcion:
      "Crema fría a base de almendras, pan y ajo, un antecedente del salmorejo con raíces árabes, servida con uvas pasas o manzana.",
    dondeProbar: [{ collection: "restaurants", id: "casa-pepe-juderia" }],
  },
  {
    id: "pastel-cordobes",
    nombre: "Pastel cordobés",
    icono: "utensils",
    tipo: "Repostería",
    descripcion:
      "Hojaldre relleno de cabello de ángel (confitura de calabaza), rematado con azúcar y canela. Existe también una versión individual llamada \"manolete\" y una variante salada con jamón.",
    dondeProbar: [
      { nombre: "Confitería Savoy", zona: "Poniente Sur, Calle Lope de Rueda" },
    ],
  },
];

const TRANSPORT = [
  {
    id: "aucorsa",
    nombre: "Autobús urbano (Aucorsa)",
    icono: "bus",
    descripcion:
      "Red de autobuses urbanos que conecta el centro histórico con el resto de la ciudad. Billete sencillo o tarjeta recargable Bus+.",
    info: "Tarifa sencilla aprox. 1,30€, bonos de varios viajes disponibles",
  },
  {
    id: "cordobici",
    nombre: "Bicicleta pública (Cordobici)",
    icono: "bike",
    descripcion:
      "Sistema de bicicletas compartidas con estaciones repartidas por la ciudad, ideal para moverse por el carril bici del centro.",
    info: "Registro necesario, primeros 30 min gratis según abono",
  },
  {
    id: "taxi",
    nombre: "Taxi",
    icono: "taxi",
    descripcion:
      "Paradas de taxi en puntos clave como la Mezquita, la estación de tren y la Plaza de las Tendillas. También disponibles por app.",
    info: "Tarifa mínima aprox. 4€, aeropuerto y polígonos con tarifa especial",
  },
  {
    id: "tren",
    nombre: "Tren (Estación de Córdoba)",
    icono: "train",
    descripcion:
      "Estación bien conectada por AVE con Madrid (menos de 2h) y Sevilla (45 min), además de servicios regionales por Andalucía.",
    info: "A 15-20 min a pie del centro histórico, o bus/taxi",
  },
  {
    id: "aeropuerto",
    nombre: "Aeropuerto",
    icono: "plane",
    descripcion:
      "Córdoba cuenta con aeropuerto propio pero con vuelos muy limitados. La opción habitual es volar a Sevilla (~140 km) y llegar en tren o autobús.",
    info: "Aeropuerto de Sevilla: aprox. 1h20 en coche o AVE/autobús",
  },
  {
    id: "parking",
    nombre: "Aparcamiento",
    icono: "parking",
    descripcion:
      "El centro histórico tiene acceso restringido a vehículos (zona ZBE). Se recomienda usar parkings públicos en el perímetro del casco antiguo.",
    info: "Parkings recomendados: San Basilio, Aparcamiento Norte, Vial Norte",
  },
];

const RESTAURANTS = [
  {
    id: "noor",
    nombre: "Noor",
    icono: "star",
    categoria: "Restaurante",
    lat: 37.8897912,
    lng: -4.7584891,
    distincion: "3 Estrellas Michelin",
    tipo: "Alta cocina andalusí de autor",
    chef: "Paco Morales",
    direccion: "Calle Pablo Ruiz Picasso, 8",
    precio: "Menú degustación desde ~240€",
    web: "https://noorrestaurant.es/",
    carta: [
      "Menú Tanwer",
      "Menú Thawra",
      "Menú Taqadum",
      "Sésamo blanco Karim con caviar del desierto",
    ],
    horario: "Mié-Sáb 13:30-15:30 20:30-23:00",
    verificar: true,
    vegetariano: false,
    conNinos: false,
    terraza: false,
    cercaJuderia: false,
  },
  {
    id: "choco",
    nombre: "Choco",
    icono: "star",
    categoria: "Restaurante",
    lat: 37.8851847,
    lng: -4.7623794,
    distincion: "1 Estrella Michelin",
    tipo: "Cocina andaluza de autor",
    chef: "Kisko García",
    direccion: "Calle Compositor Serrano Lucena, 14",
    precio: "Menú degustación de gama alta",
    web: "https://restaurantechoco.com/",
    carta: [
      "Menús degustación de temporada",
      "Cocina de raíces andaluzas con técnica actual",
      "Maridaje con vinos de la D.O. Montilla-Moriles",
    ],
    horario: "Mié-Sáb 13:30-15:00 20:30-22:00, Dom 13:30-15:00",
    vegetariano: false,
    conNinos: false,
    terraza: false,
    cercaJuderia: false,
  },
  {
    id: "el-churrasco",
    nombre: "El Churrasco",
    icono: "utensils",
    categoria: "Restaurante",
    lat: 37.8800938,
    lng: -4.7819054,
    distincion: "Selección Guía Michelin",
    tipo: "Cocina cordobesa tradicional (parrilla)",
    direccion: "Calle Romero, 16 (Judería)",
    precio: "Medio-alto",
    web: "https://elchurrasco.com/",
    carta: [
      "Churrasco cordobés con salsas roja y verde",
      "Rabo de toro",
      "Gazpacho blanco con piñones",
      "Solomillo ibérico a la brasa",
    ],
    horario: "Todos los días 13:00-16:00 20:00-23:30",
    vegetariano: true,
    conNinos: true,
    terraza: false,
    cercaJuderia: true,
  },
  {
    id: "bodegas-campos",
    nombre: "Bodegas Campos",
    icono: "utensils",
    categoria: "Restaurante",
    lat: 37.8808857,
    lng: -4.7740519,
    distincion: "Taberna histórica desde 1908",
    tipo: "Cocina cordobesa tradicional",
    direccion: "Calle Lineros, 32",
    precio: "Medio-alto",
    web: "https://bodegascampos.com/",
    carta: [
      "Rabo de toro",
      "Ensalada molinera con bacalao y naranja",
      "Manitas rellenas de foie y jamón",
      "Leche frita con helado de canela",
    ],
    horario: "Lun-Sáb 13:00-16:00 20:00-23:00",
    verificar: true,
    vegetariano: false,
    conNinos: true,
    terraza: false,
    cercaJuderia: false,
    esHistorica: true,
    historia:
      "Fundada en 1908 por Domingo Campos del Santo como bodega de vinos; sus comedores no se abrieron hasta 1964. Conserva patios andaluces centenarios y una completa colección de vinos de Montilla-Moriles.",
    queDeberiaPedir: "El rabo de toro y la ensalada molinera con bacalao y naranja, maridados con un fino de la casa.",
  },
  {
    id: "taberna-salinas",
    nombre: "Taberna Salinas",
    icono: "utensils",
    categoria: "Restaurante",
    lat: 37.8841313,
    lng: -4.7758244,
    distincion: "Taberna histórica desde 1924",
    tipo: "Cocina cordobesa tradicional",
    direccion: "Calle Tundidores, 3",
    precio: "Económico-medio",
    web: "http://www.tabernasalinas.com/",
    carta: [
      "Ajo blanco",
      "Flamenquín",
      "Rabo de toro estofado",
      "Berenjenas fritas con miel de caña",
    ],
    horario: "Lun-Vie 12:30-16:00 20:00-23:30, Sáb 12:30-16:00",
    vegetariano: true,
    conNinos: true,
    terraza: false,
    cercaJuderia: false,
    esHistorica: true,
    historia:
      "Abierta en 1924 por Francisco de Paula Salinas junto al mercado de abastos; cerró en 1982 y reabrió en 1988 de la mano de Manuel Jiménez Montoro. Su patio con azulejos es uno de los más fotografiados de la ciudad.",
    queDeberiaPedir: "El ajo blanco de entrante y el flamenquín como plato principal.",
  },
  {
    id: "casa-pepe-juderia",
    nombre: "Casa Pepe de la Judería",
    icono: "utensils",
    categoria: "Restaurante",
    lat: 37.8798604,
    lng: -4.7815207,
    distincion: "Selección Guía Michelin, desde 1928",
    tipo: "Cocina cordobesa tradicional",
    direccion: "Calle Romero, 1 (Judería)",
    precio: "Medio",
    web: "https://restaurantecasapepedelajuderia.com/",
    carta: [
      "Salmorejo cordobés",
      "Flamenquín",
      "Rabo de toro",
      "Mazamorra",
      "Berenjenas con miel de caña",
    ],
    horario: "Dom-Jue 13:00-16:00 20:00-23:00, Vie-Sáb 13:00-16:00 20:00-24:00",
    vegetariano: true,
    conNinos: true,
    terraza: false,
    cercaJuderia: true,
    esHistorica: true,
    historia:
      "Taberna familiar abierta en 1928 en pleno corazón de la Judería, muy cerca de la Sinagoga, reconocida por la Guía Michelin por su cocina cordobesa tradicional.",
    queDeberiaPedir: "El salmorejo y la mazamorra de postre: dos versiones de la misma receta con siglos de diferencia.",
  },
  {
    id: "cuchara-san-lorenzo",
    nombre: "La Cuchara de San Lorenzo",
    icono: "utensils",
    categoria: "Restaurante",
    lat: 37.8873563,
    lng: -4.7688616,
    distincion: "Bib Gourmand, Guía Michelin",
    tipo: "Cocina cordobesa de mercado",
    direccion: "Calle Arroyo de San Lorenzo, 2",
    precio: "Medio (~35€ por persona)",
    web: "https://lacucharadesanlorenzo.es/",
    carta: ["Salmorejo", "Croquetas de ternera", "Mini patatas bravas", "Flamenquín", "Rabo de toro", "Mazamorra"],
    horario: "Mar-Dom 14:00-16:00 21:00-23:00",
    verificar: true,
    vegetariano: true,
    conNinos: true,
    terraza: false,
    cercaJuderia: false,
  },
  {
    id: "puerta-sevilla",
    nombre: "Restaurante Puerta Sevilla",
    icono: "utensils",
    categoria: "Restaurante",
    lat: 37.8751531,
    lng: -4.7854436,
    distincion: "Casa señorial centenaria",
    tipo: "Cocina cordobesa tradicional",
    direccion: "Calle Postrera, 51 (San Basilio)",
    precio: "Medio (menú del día ~20€)",
    web: "https://gruporosalescordoba.com/restaurante-puerta-sevilla/",
    carta: ["Berenjenas con miel", "Flamenquín", "Pescado fresco del día", "Menú del día entre semana"],
    horario: "Todos los días 13:00-16:30 20:00-23:30",
    vegetariano: true,
    conNinos: true,
    terraza: false,
    cercaJuderia: false,
  },
  {
    id: "ermita-candelaria",
    nombre: "Ermita de la Candelaria",
    icono: "utensils",
    categoria: "Restaurante",
    lat: 37.8821932,
    lng: -4.7738550,
    distincion: "Instalado en una ermita del siglo XV",
    tipo: "Cocina cordobesa de autor",
    direccion: "Calle Candelaria, 2",
    precio: "Medio-alto",
    web: "https://ermitacandelaria.com/",
    carta: ["Pisto casero", "Alcachofas a la montillana", "Perdiz encebollada"],
    horario: "Mar-Dom 13:30-16:00 20:30-24:00",
    verificar: true,
    vegetariano: true,
    conNinos: true,
    terraza: false,
    cercaJuderia: false,
  },
  {
    id: "almudaina",
    nombre: "Restaurante Almudaina",
    icono: "utensils",
    categoria: "Restaurante",
    lat: 37.8780473,
    lng: -4.7818851,
    distincion: "Palacio del siglo XVI, en la Judería",
    tipo: "Cocina cordobesa tradicional",
    direccion: "Plaza Campo Santo de los Mártires, 1 (Judería)",
    precio: "Medio-alto",
    web: "https://restaurantealmudaina.com/",
    carta: [
      "Salmorejo cordobés",
      "Flamenquín cordobés",
      "Rabo de toro estilo Almudaina",
      "Tajín de cordero lechal con ciruelas",
      "Milhoja de berenjena con foie y queso de cabra",
    ],
    vegetariano: true,
    conNinos: true,
    terraza: true,
    cercaJuderia: true,
  },
  {
    id: "casa-mazal",
    nombre: "Casa Mazal",
    icono: "utensils",
    categoria: "Restaurante",
    lat: 37.8792359,
    lng: -4.7824135,
    distincion: "Cocina sefardí en un caserón del siglo XIV",
    tipo: "Cocina sefardí y andalusí",
    direccion: "Calle Tomás Conde, 3 (Judería)",
    precio: "Medio-alto",
    web: "https://casamazal.es/",
    carta: ["Menús degustación sefardíes y andalusíes", "Platos vegetarianos y veganos", "Postres sin lácteos"],
    horario: "Lun-Mar 12:30-16:00 19:30-23:30, Jue 12:30-16:00 19:30-23:30, Vie-Dom 12:30-23:30",
    vegetariano: true,
    conNinos: true,
    terraza: true,
    cercaJuderia: true,
  },
];

const TAPAS = [
  {
    id: "bodegas-mezquita-cespedes",
    nombre: "Bodegas Mezquita Céspedes",
    icono: "trophy",
    categoria: "Tapas",
    lat: 37.8799836,
    lng: -4.7800481,
    distincion: "Mejor restaurante del mundo 2025 (TripAdvisor Traveler's Choice)",
    tipo: "Bar de tapas andaluzas",
    direccion: "Calle Céspedes (Judería)",
    precio: "Económico-medio",
    web: "https://www.bodegasmezquita.com/",
    carta: [
      "Salmorejo cordobés",
      "Berenjenas califales al PX",
      "Rabo de toro a la cordobesa",
    ],
    horario: "Todos los días 12:30-24:00",
    vegetariano: true,
    conNinos: true,
    terraza: false,
    cercaJuderia: true,
  },
  {
    id: "casa-rubio",
    nombre: "Casa Rubio",
    icono: "utensils",
    categoria: "Tapas",
    lat: 37.8807125,
    lng: -4.7838236,
    distincion: "Taberna histórica desde 1920",
    tipo: "Bar de tapas con terraza en azotea",
    direccion: "Puerta de Almodóvar (Judería)",
    precio: "Económico-medio",
    web: "https://restaurantecasarubiocordoba.com/",
    carta: [
      "Berenjenas fritas con miel de caña",
      "Rabo de toro con patatas",
      "Tapas de raíz sefardí",
    ],
    horario: "Lun 13:00-16:00 20:00-23:00, Jue-Dom 13:00-16:00 20:00-23:00",
    vegetariano: true,
    conNinos: true,
    terraza: true,
    cercaJuderia: true,
    esHistorica: true,
    historia:
      "Abierta en 1920 como \"Taberna de El Cojo de San Nicolás\" junto a la Puerta de Almodóvar; en 1932 José María Jiménez Márquez la compró y le dio el nombre de Casa Rubio, con el que sigue funcionando.",
    queDeberiaPedir: "Las berenjenas fritas con miel de caña en la terraza de la azotea, con vistas a la muralla.",
  },
  {
    id: "sociedad-plateros",
    nombre: "Sociedad de Plateros (San Francisco)",
    icono: "utensils",
    categoria: "Tapas",
    lat: 37.8811175,
    lng: -4.7756118,
    distincion: "Taberna cordobesa desde 1872",
    tipo: "Taberna tradicional con patio",
    direccion: "Calle Romero Barros, 6",
    precio: "Económico",
    web: "https://tabernaplateros.com/",
    carta: ["Salmorejo", "Guisos caseros de cuchara", "Vinos de Montilla-Moriles"],
    horario: "Mar-Sáb 11:00-16:00 20:00-23:30, Dom 11:30-17:00",
    vegetariano: true,
    conNinos: true,
    terraza: true,
    cercaJuderia: false,
    esHistorica: true,
    historia:
      "La sociedad mutualista de plateros nació en 1868 y su taberna abrió en 1872 junto al convento de San Francisco, en lo que hoy es una de las tabernas más veteranas de Córdoba.",
    queDeberiaPedir: "El salmorejo y algún guiso casero de cuchara del día, acompañados de un vino de Montilla-Moriles.",
  },
  {
    id: "bar-santos",
    nombre: "Bar Santos",
    icono: "utensils",
    categoria: "Tapas",
    lat: 37.8799749,
    lng: -4.7792390,
    distincion: "Icónico desde 1966, junto a la Mezquita",
    tipo: "Bar de tapas de barra (solo efectivo)",
    direccion: "Calle Magistral González Francés, 3",
    precio: "Económico",
    web: "https://www.facebook.com/barsantosCordoba/",
    carta: ["Tortilla de patatas gigante", "Tapas frías de barra"],
    horario: "Lun-Jue 10:00-24:00, Vie-Dom 11:00-24:00",
    vegetariano: true,
    conNinos: false,
    terraza: false,
    cercaJuderia: true,
    esHistorica: true,
    historia:
      "Bar de barra abierto en 1966 pegado a la Mezquita-Catedral, célebre por su tortilla de patatas gigante que se sirve en porciones y solo se paga en efectivo.",
    queDeberiaPedir: "Una ración de tortilla de patatas para comer de pie, mirando la muralla de la Mezquita.",
  },
  {
    id: "bodega-guzman",
    nombre: "Bodega Guzmán",
    icono: "wine",
    categoria: "Tapas",
    lat: 37.8804554,
    lng: -4.7836796,
    distincion: "Bodega centenaria en la Judería",
    tipo: "Bodega de vinos a granel",
    direccion: "Calle Judíos, 7",
    precio: "Económico",
    carta: ["Vino Amargoso y Fino a granel", "Salmorejo", "Embutidos y tapas frías"],
    vegetariano: true,
    conNinos: false,
    terraza: false,
    cercaJuderia: true,
  },
  {
    id: "cerveceria-califa",
    nombre: "Cervecería Califa",
    icono: "wine",
    categoria: "Tapas",
    lat: 37.8827040,
    lng: -4.7794722,
    distincion: "Primera fábrica de cerveza artesanal de Córdoba",
    tipo: "Cervecería artesanal con fábrica propia",
    direccion: "Calle Juan Valera, 3",
    precio: "Económico-medio",
    web: "https://cervezascalifa.com/",
    carta: ["Lager Premium", "Roja Tostada", "Doble Malta", "Punch IPA", "Croquetas y tabla de quesos"],
    horario: "Lun-Jue 11:00-16:00 19:00-02:00",
    verificar: true,
    vegetariano: false,
    conNinos: false,
    terraza: true,
    cercaJuderia: false,
  },
  {
    id: "trapperia-beer-shop",
    nombre: "La Trapperia Beer Shop",
    icono: "wine",
    categoria: "Tapas",
    lat: 37.8848248,
    lng: -4.7776053,
    distincion: "Especializada solo en cerveza",
    tipo: "Cervecería con selección rotativa nacional e importada",
    direccion: "Calle García Lovera, 5",
    precio: "Económico-medio",
    carta: ["Cervezas artesanas rotativas", "Tapas y raciones para compartir"],
    horario: "Mar-Sáb 12:15-16:00 20:00-23:30, Lun 20:00-23:30",
    verificar: true,
    vegetariano: false,
    conNinos: false,
    terraza: false,
    cercaJuderia: false,
  },
  {
    id: "rafa-jimenez-cerveceria",
    nombre: "Rafa Jiménez Cervecería",
    icono: "wine",
    categoria: "Tapas",
    lat: 37.8990458,
    lng: -4.7833122,
    distincion: "Conocida por su amplia terraza",
    tipo: "Cervecería con selección nacional e internacional",
    direccion: "Calle Escultor Fernández Márquez, 1",
    precio: "Medio",
    web: "https://rafajimenezcerveceria.es/",
    carta: ["Flamenquín", "Croquetas", "Amplia selección de cervezas"],
    horario: "Mar-Dom 8:30-24:00",
    verificar: true,
    vegetariano: false,
    conNinos: true,
    terraza: true,
    cercaJuderia: false,
  },
  {
    id: "taberna-fuenseca",
    nombre: "Taberna La Fuenseca",
    icono: "utensils",
    categoria: "Tapas",
    lat: 37.8875558,
    lng: -4.7751528,
    distincion: "Taberna histórica desde 1852",
    tipo: "Taberna tradicional y peña flamenca",
    direccion: "Calle Juan Rufo, 20",
    precio: "Económico",
    carta: ["Salmorejo", "Flamenquín", "Rabo de toro", "Mazamorra", "Berenjenas con miel", "Jamón ibérico"],
    vegetariano: true,
    conNinos: true,
    terraza: false,
    cercaJuderia: false,
    esHistorica: true,
    historia:
      "Abierta en 1852, es una de las tabernas más veteranas de Córdoba y una peña flamenca viva: el cante puede surgir de forma espontánea entre los parroquianos, sin escenario ni horario fijo.",
    queDeberiaPedir: "Salmorejo y flamenquín, acompañados de un fino de Montilla-Moriles, con suerte de que alguien empiece a cantar.",
  },
  {
    id: "casa-bravo-1919",
    nombre: "Casa Bravo 1919",
    icono: "utensils",
    categoria: "Tapas",
    lat: 37.8808156,
    lng: -4.7836554,
    distincion: "Taberna histórica desde 1919",
    tipo: "Taberna tradicional junto a la Puerta de Almodóvar",
    direccion: "Puerta de Almodóvar, 1 (Judería)",
    precio: "Económico",
    carta: [
      "Rabo de toro",
      "Salmorejo",
      "Menudillos al ajillo",
      "Callos cortijeros con manitas",
      "Flamenquín casero",
      "Pastel cordobés",
    ],
    horario: "Todos los días 12:00-16:30 20:00-24:00",
    verificar: true,
    vegetariano: true,
    conNinos: true,
    terraza: false,
    cercaJuderia: true,
    esHistorica: true,
    historia:
      "Fundada en 1919 junto a la Puerta de Almodóvar, conserva el azulejo original de 1914 con motivos de la Mezquita. Familiar desde su apertura.",
    queDeberiaPedir: "El rabo de toro y los menudillos al ajillo, terminando con un pastel cordobés de postre.",
  },
  {
    id: "casa-el-pisto",
    nombre: "Taberna San Miguel \"Casa El Pisto\"",
    icono: "utensils",
    categoria: "Tapas",
    lat: 37.8859026,
    lng: -4.7795889,
    distincion: "Taberna histórica desde 1880",
    tipo: "Taberna tradicional ligada al mundo del toreo",
    direccion: "Plaza de San Miguel, 1",
    precio: "Económico-medio",
    web: "https://casaelpisto.com/",
    carta: ["Pisto", "Rabo de toro", "Manitas de cerdo", "Carrillada ibérica al vino viejo"],
    horario: "Lun-Sáb 12:00-16:00 20:00-24:00",
    vegetariano: true,
    conNinos: true,
    terraza: false,
    cercaJuderia: false,
    esHistorica: true,
    historia:
      "Abierta en 1880 en la Plaza de San Miguel, ha estado ligada históricamente al mundo del toreo: entre sus parroquianos estuvo el padre del mítico Manolete. La familia López-Acedo la regenta desde 1974.",
    queDeberiaPedir: "El pisto que da nombre a la casa y el rabo de toro.",
  },
  {
    id: "taberna-regina",
    nombre: "Taberna Regina",
    icono: "utensils",
    categoria: "Tapas",
    lat: 37.8848415,
    lng: -4.7713060,
    distincion: "Taberna histórica desde 1904",
    tipo: "Taberna tradicional con patio cordobés",
    direccion: "Plaza de Regina / Calle Encarnación Agustina, 2",
    precio: "Económico-medio",
    carta: ["Patatas bravas", "Carne al Jerez", "Callos", "Rabo de toro", "Salmorejo", "Flamenquín"],
    vegetariano: true,
    conNinos: true,
    terraza: true,
    cercaJuderia: false,
    esHistorica: true,
    historia:
      "Abierta en 1904, conservaba antiguamente una entrada discreta separada para mujeres, un detalle social de la época que hoy forma parte de su historia.",
    queDeberiaPedir: "Las patatas bravas y la carne al Jerez, en su terraza o en el patio cordobés.",
  },
  {
    id: "bar-santa-marina",
    nombre: "Bar Santa Marina",
    icono: "utensils",
    categoria: "Tapas",
    lat: 37.8900080,
    lng: -4.7752049,
    distincion: "Uno de los bares más veteranos de Córdoba",
    tipo: "Bar de barrio en el histórico Santa Marina",
    direccion: "Calle Mayor de Santa Marina, 1",
    precio: "Económico",
    carta: ["Salmorejo", "Flamenquín", "Pinchos morunos", "Berenjenas con miel", "Croquetas de boletus"],
    horario: "Lun-Vie 7:00-16:30, Sáb 9:00-15:30",
    vegetariano: true,
    conNinos: false,
    terraza: true,
    cercaJuderia: false,
  },
];
